"""remove unique constraint from refresh token db

Revision ID: 924eed278d58
Revises: dd2f6a5de7fe
Create Date: 2026-02-14 18:06:31.015661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924eed278d58'
down_revision: Union[str, Sequence[str], None] = 'dd2f6a5de7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_tokens_unique_constraint'), 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('refresh_tokens_unique_constraint'), 'refresh_tokens', ['user_id', 'session_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
